export const SET_SEARCH_TERM = 'SET_SEARCH_TERM';
export const IMAGES_FETCH_REQUESTED = 'IMAGES_FETCH_REQUESTED';
export const IMAGES_FETCH_SUCCEEDED = 'IMAGES_FETCH_SUCCEEDED';
export const IMAGES_FETCH_FAILED = 'IMAGES_FETCH_FAILED';
export const REQUESTED = 1;
export const SUCCEEDED = 2;
export const FAILED = 3;
